import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "material-symbols";

export const metadata = {
  title: "صفحه اصلی فروشگاه",
  description: "طراحی مدرن فروشگاه اینترنتی",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="scroll-smooth light">
      <head>
        <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
        <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-background-light dark:bg-background-dark text-gray-800 dark:text-gray-100 font-display min-h-screen flex flex-col overflow-x-hidden selection:bg-primary selection:text-white antialiased">
        {children}
      </body>
    </html>
  );
}
